<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../_roslyn/CodeMapExtractorSupport.cs" Link="CodeMapExtractorSupport.cs" />
    <Compile Include="../_roslyn/DotNetWorkspace.cs" Link="DotNetWorkspace.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="17.13.26" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Framework" Version="17.13.26" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Locator" Version="1.7.8" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="17.13.26" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.13.26" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.13.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.13.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.18" />
  </ItemGroup>
</Project>
